In [1]:
import s3fs
import numpy as np
import pandas as pd

from mvpa2.datasets.mri import fmri_dataset
from mvpa2.clfs.meta import SplitClassifier
from mvpa2.generators.partition import NFoldPartitioner
from mvpa2 import cfg
from mvpa2.clfs.svm import libsvm
import mvpa2.datasets as md
from mvpa2.featsel.base import SensitivityBasedFeatureSelection
from mvpa2.clfs.warehouse import OneWayAnova
from mvpa2.clfs.warehouse import FixedNElementTailSelector
from mvpa2.clfs.meta import FeatureSelectionClassifier
from mvpa2.datasets.mri import map2nifti

from mvpa2.mappers.fx import maxofabs_sample

/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/datasets/base.py:465: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def __init__(self, shape=None, sid=None, fid=None, dtype=np.float):


In [2]:
## Load the data file names
fs = s3fs.S3FileSystem(anon=True)
ll = fs.ls('natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR')
sess_beta_list = [l for l in ll if l.split('/')[6].startswith("betas") and l.endswith("nii.gz")]

behav_data = pd.read_csv('subj01/behav/final_response.tsv', sep='\t')

In [3]:
sess_beta_list

['natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session01.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session02.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session03.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session04.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session05.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session06.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session07.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fithrf_GLMdenoise_RR/betas_session08.nii.gz',
 'natural-scenes-dataset/nsddata_betas/ppdata/subj01/func1pt8mm/betas_fi

In [4]:
behav_data

SUBJECT  SESSION  RUN  TRIAL  73KID  10KID        TIME  ISOLD  \
0            1        1    1      1  46003    626    0.505082      0   
1            1       18    1     53  46003    626  133.667932      1   
2            1       35    6     24  46003    626  239.717843      1   
3            1        1    1      2  61883   5013    0.505128      0   
4            1       13    2     26  61883   5013   91.617241      1   
...        ...      ...  ...    ...    ...    ...         ...    ...   
29995        1       40    9     46  52260   7543  262.615194      1   
29996        1       40   11     30  52260   7543  262.623441      1   
29997        1       40    9     24  37847   8122  262.614083      0   
29998        1       40   10     13  37847   8122  262.618065      1   
29999        1       40   12     30  37847   8122  262.628162      1   

       ISCORRECT           RT  ...  ISOLDCURRENT  ISCORRECTCURRENT  TOTAL1  \
0            1.0   803.529781  ...             0               1.0       1   
1            0.0  1749.405303  ...             0               1.0       1   
2            0.0  1202.503384  ...             0               1.0       1   
3            1.0   972.261383  ...             0               1.0       1   
4            1.0  2411.506844  ...             0               0.0       1   
...          ...          ...  ...           ...               ...     ...   
29995        1.0   701.858252  ...             1               1.0       0   
29996        1.0   579.064407  ...             1               1.0       0   
29997        0.0   902.196521  ...             0               0.0       0   
29998        1.0   657.601719  ...             1               1.0       0   
29999        1.0   684.500020  ...             1               1.0       0   

       TOTAL2  BUTTON  MISSINGDATA  people_count  animal_count  shared1000  \
0           0     1.0            0             0            14        True   
1           0     1.0            0             0            14        True   
2           0     1.0            0             0            14        True   
3           0     1.0            0             9             0       False   
4           1     2.0            0             9             0       False   
...       ...     ...          ...           ...           ...         ...   
29995       1     2.0            0            13             7       False   
29996       1     2.0            0            13             7       False   
29997       1     2.0            0             1             0       False   
29998       1     2.0            0             1             0       False   
29999       1     2.0            0             1             0       False   

       interaction_type  
0                   NaN  
1                   NaN  
2                   NaN  
3                   NaN  
4                   NaN  
...                 ...  
29995               NaN  
29996               NaN  
29997               NaN  
29998               NaN  
29999               NaN  

[30000 rows x 23 columns]

In [5]:
### Load the data
# load the first session
sess = 1
sess_fname = sess_beta_list[0]
print(f"Loading session {sess} data ...")
# load the session data
fs.get(sess_fname, "tmp.nii.gz")
sess_data = fmri_dataset("tmp.nii.gz", mask = "TPJfunc.nii")

# extract the behavioral data for the session
tmp_behav = behav_data[behav_data['SESSION'] == sess] 

# only take the trials that have an interaction_type (i.e., not null)
indices = tmp_behav['interaction_type'].notnull().tolist()

# take the beta values for those trials
all_sess_ds = sess_data[indices, :]

# add the target (interaction_type) and chunk (session) information to the dataset
targets = tmp_behav[indices]['interaction_type'].tolist()
chunks = tmp_behav[indices]['SESSION']

all_sess_ds.sa['targets'] = targets
all_sess_ds.sa['chunks'] = chunks

# add an attribute that determines whether the session should be included in the training or test dataset
if (sess) >=36:
    all_sess_ds.sa['train_or_test'] = ['test'] * len(all_sess_ds)
else:
    all_sess_ds.sa['train_or_test'] = ['train'] * len(all_sess_ds)
    
# add the 73KID as an attribute
all_sess_ds.sa['ID'] = tmp_behav[indices]['73KID']

# then concatenate the other sessions to the first session
for sess, sess_fname in enumerate(sess_beta_list[1:37]): 
    print(f"Loading session {sess+2} data ...")
    # load the session data
    fs.get(sess_fname, "tmp.nii.gz")
    sess_data = fmri_dataset("tmp.nii.gz", mask = "TPJfunc.nii")

    # extract the behavioral data for the session
    tmp_behav = behav_data[behav_data['SESSION'] == (sess+2)] 

    # only take the trials that have an interaction_type (i.e., not null)
    indices = tmp_behav['interaction_type'].notnull().tolist()

    # take the beta values for those trials
    tmp_ds = sess_data[indices, :]

    # add the target (interaction_type) and chunk (session) information to the dataset
    targets = tmp_behav[indices]['interaction_type'].tolist()
    chunks = tmp_behav[indices]['SESSION']
    tmp_ds.sa['targets'] = targets
    tmp_ds.sa['chunks'] = chunks
    
    # add an attribute that determines whether the session should be included in the training or test dataset
    if (sess+2) >=36:
        tmp_ds.sa['train_or_test'] = ['test'] * len(tmp_ds)
    else:
        tmp_ds.sa['train_or_test'] = ['train'] * len(tmp_ds)
        
    # add the 73KID as an attribute
    tmp_ds.sa['ID'] = tmp_behav[indices]['73KID']
    
    # concatenate the tmp_ds to the all_sess_ds
    all_sess_ds = md.vstack((all_sess_ds, tmp_ds))

Loading session 1 data ...


/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/datasets/mri.py:78: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  data, header = img.get_data(), img.header


 * Please note: warnings are printed only once, but underlying problem might occur many times *
Loading session 2 data ...
Loading session 3 data ...
Loading session 4 data ...
Loading session 5 data ...
Loading session 6 data ...
Loading session 7 data ...
Loading session 8 data ...
Loading session 9 data ...
Loading session 10 data ...
Loading session 11 data ...
Loading session 12 data ...
Loading session 13 data ...
Loading session 14 data ...
Loading session 15 data ...
Loading session 16 data ...
Loading session 17 data ...
Loading session 18 data ...
Loading session 19 data ...
Loading session 20 data ...
Loading session 21 data ...
Loading session 22 data ...
Loading session 23 data ...
Loading session 24 data ...
Loading session 25 data ...
Loading session 26 data ...
Loading session 27 data ...
Loading session 28 data ...
Loading session 29 data ...
Loading session 30 data ...
Loading session 31 data ...
Loading session 32 data ...
Loading session 33 data ...
Loading session 

In [6]:
print(f"Dataset shape is: {all_sess_ds.shape}")

Dataset shape is: (634, 1000)


In [7]:
# all_sess_ds.samples

In [8]:
## convert the integer values to percent change (according to https://cvnlab.slite.com/p/6CusMRYfk0/Functional-data-NSD)
normalized_all_sess_ds = all_sess_ds.copy()
normalized_all_sess_ds.samples = normalized_all_sess_ds.samples.astype('float')/300
# normalized_all_sess_ds.samples

In [24]:
## The classification procedure
num_features = 300
fsel = SensitivityBasedFeatureSelection(OneWayAnova(), 
                                        FixedNElementTailSelector(num_features, mode='select', tail='upper'))
clf = libsvm.SVM()
clf = FeatureSelectionClassifier(clf, fsel)
sclf = SplitClassifier(clf, NFoldPartitioner(cvtype=1), enable_ca=['stats'])
cv_sensana = sclf.get_sensitivity_analyzer()

In [25]:
## Apply the classifier
sens = cv_sensana(normalized_all_sess_ds[normalized_all_sess_ds.sa.train_or_test=='train'])
sens_comb = sens.get_mapped(maxofabs_sample())

/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/misc/attrmap.py:171: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  num = np.empty(attr.shape, dtype=np.int)


In [26]:
print(cv_sensana.clf.ca.stats.matrix)

[[  6   9  19]
 [ 31  55  61]
 [128 131 151]]


/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/clfs/transerror.py:714: RuntimeWarning: invalid value encountered in true_divide
  for m in mat_all]
/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/clfs/transerror.py:718: RuntimeWarning: invalid value encountered in true_divide
  for m in mat_all]


In [27]:
print(cv_sensana.clf.ca.stats.as_string(description=True))

----------.
predictions\targets   Joint attention    Social interaction   Unrelated people
            `------  ------------------  ------------------  ------------------  P'   N'     FP     FN    PPV  NPV  TPR  SPC  FDR  MCC   F1
  Joint attention            6                   9                   19          34   365    28     159  0.18 0.56 0.04 0.88 0.82 -0.11 0.06
 Social interaction          31                  55                  61         147   297    92     140  0.37 0.53 0.28 0.63 0.63 -0.07 0.32
  Unrelated people          128                 131                 151         410   141    259    80   0.37 0.43 0.65 0.19 0.63 -0.17 0.47
Per target:          ------------------  ------------------  ------------------
         P                  165                 195                 231
         N                  426                 396                 360
         TP                  6                   55                 151
         TN                 206                 15

In [23]:
## Plot the weights outputted by the classifier
senstime = fs.ls('natural-scenes-dataset/nsddata_timeseries/ppdata/subj01/func1pt8mm/timeseries/timeseries_session01_run01.nii.gz')
sens = senstime[0]
fs.get(sens, "sens.nii.gz")
sensd = fmri_dataset("sens.nii.gz", mask="TPJfunc.nii")

sensd.shape

nimg = map2nifti(sensd, sens_comb)
nimg.to_filename('SVM.nii')

/srv/conda/envs/notebook/lib/python3.7/site-packages/mvpa2/datasets/mri.py:78: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  data, header = img.get_data(), img.header
